import appColors from '@src/theme/appColors';
import appFonts from '@src/theme/appFonts';
import { SF, SH, SW } from '@src/theme/dimensions';
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: appColors.boxBg,
  },
  headerWrap: {
    backgroundColor: appColors.white,
    borderBottomLeftRadius: SW(30),
    borderBottomRightRadius: SW(30),
    elevation: 8,
    shadowColor: 'rgba(0, 0, 0, 0.3)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
  },
  header: {
    paddingHorizontal: SW(20),
    paddingTop: SH(30),
    paddingBottom: SH(30),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: appColors.DarkBg,
    borderBottomLeftRadius: SH(30),
    borderBottomRightRadius: SH(30),
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  timeText: {
    fontSize: SF(14),
    color: appColors.white,
    fontFamily: appFonts.PoppinsSemiBold,
    marginRight: SW(15),
    opacity: 0.5,
  },
  title: {
    fontSize: SF(18),
    color: appColors.white,
    fontFamily: appFonts.PoppinsSemiBold,
    marginLeft: SW(10),
  },
  body: {
    flex: 1,
    paddingVertical: SH(20),
    paddingHorizontal: SW(20),
  },
  profileCircle: {
    width: SW(100),
    height: SW(100),
    borderRadius: SW(100),
    backgroundColor: appColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: SH(10),
    position: 'relative',
    overflow: 'hidden',
  },
  profileInitials: {
    fontSize: SF(30),
    color: appColors.black,
    fontFamily: appFonts.PoppinsBold,
  },
  uploadButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    left: 0,
    backgroundColor: appColors.blackTransparent,
    padding: SW(8),
    alignItems: 'center',
  },
  label: {
    fontSize: SF(13),
    color: appColors.bodyText_2,
    fontFamily: appFonts.PoppinsMedium,
    marginTop: SH(10),
  },
  verifiedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: SH(5),
    backgroundColor: appColors.white,
    borderRadius: SW(10),
    paddingVertical: SW(10),
    paddingHorizontal: SW(15),
    borderWidth: 1,
    borderColor: appColors.textInput_2,
  },
  inputField: {},
  value: {
    fontSize: SF(14),
    color: appColors.bodyText,
    fontFamily: appFonts.PoppinsRegular,
  },
  verificationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: SH(5),
  },
  verifyButton: {
    backgroundColor: appColors.lightBlue,
    paddingLeft: SW(15),
    borderRadius: SW(10),
  },
  verifyText: {
    fontSize: SF(14),
    color: appColors.white,
    fontFamily: appFonts.PoppinsSemiBold,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: appColors.white,
    padding: SW(20),
    borderRadius: SW(10),
    width: '80%',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: SF(18),
    color: appColors.DarkBg,
    fontFamily: appFonts.PoppinsSemiBold,
    marginBottom: SH(10),
  },
  closeButton: {
    position: 'absolute',
    top: SH(10),
    right: SW(10),
  },
  emailImage: {
    width: SW(86),
    height: SW(70),
    marginBottom: SW(30),
  },
  modalText: {
    fontSize: SF(16),
    color: appColors.darkTheme,
    fontFamily: appFonts.PoppinsMedium,
    textAlign: 'center',
  },
  modalSubText: {
    fontSize: SF(12),
    color: appColors.bodyText_2,
    fontFamily: appFonts.PoppinsRegular,
    textAlign: 'center',
    marginVertical: SH(10),
  },
  inputContainer: {
    width: '100%',
    marginVertical: SH(10),
  },
  inputLabel: {
    fontSize: SF(13),
    color: appColors.darkTheme,
    fontFamily: appFonts.PoppinsMedium,
    marginBottom: SH(5),
  },
  verifyCodeButton: {
    backgroundColor: appColors.DarkBg,
    paddingVertical: SH(10),
    paddingHorizontal: SW(20),
    borderRadius: SW(16),
    width: '100%',
    alignItems: 'center',
    marginTop: SH(10),
  },
  tryAgainText: {
    fontSize: SF(12),
    color: appColors.DarkBg,
    fontFamily: appFonts.PoppinsRegular,
    textAlign: 'center',
    marginTop: SH(10),
  },
  saveButton: {
    marginHorizontal: SW(50),
    backgroundColor: appColors.DarkPrimary,
    padding: SW(12),
    borderRadius: SW(16),
  },
  saveText: {
    color: appColors.white,
    textAlign: 'center',
    fontFamily: appFonts.PoppinsSemiBold,
    fontSize: SF(13),
  },
});

export default styles;
